// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: codeinterpreter/codeinterpreter.proto

// Package codeinterpreter is the ConnectRPC contract for running code in the stateful
// Python kernel (Stage 11), matching E2B's separate code-interpreter service. Execute is
// server-streaming: it streams OutputEvents (stdout / stderr / error / end) as the cell
// runs -- the Connect-over-HTTP/1.1 equivalent of the Stage-7 daemon's /execute SSE.
// Implemented in 11b (the kernel moves here onto its own vsock port). See docs/STAGE11_DESIGN.md.

package codeinterpreter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language       string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`                                     // "" = python
	TimeoutSeconds float64                `protobuf:"fixed64,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 = default (30s)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_codeinterpreter_codeinterpreter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codeinterpreter_codeinterpreter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_codeinterpreter_codeinterpreter_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteRequest) GetTimeoutSeconds() float64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// OutputEvent mirrors protocol.py's OutputEvent. type is one of stdout|stderr|error|end;
// exit_code is meaningful only on the "end" event (0 ok, 1 raised, -1 timeout) and ignored
// otherwise -- so a plain int32 (default 0) reproduces the prior "only on end" semantics.
type OutputEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputEvent) Reset() {
	*x = OutputEvent{}
	mi := &file_codeinterpreter_codeinterpreter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputEvent) ProtoMessage() {}

func (x *OutputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_codeinterpreter_codeinterpreter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputEvent.ProtoReflect.Descriptor instead.
func (*OutputEvent) Descriptor() ([]byte, []int) {
	return file_codeinterpreter_codeinterpreter_proto_rawDescGZIP(), []int{1}
}

func (x *OutputEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutputEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *OutputEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

var File_codeinterpreter_codeinterpreter_proto protoreflect.FileDescriptor

const file_codeinterpreter_codeinterpreter_proto_rawDesc = "" +
	"\n" +
	"%codeinterpreter/codeinterpreter.proto\x12\x0fcodeinterpreter\"i\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x01R\x0etimeoutSeconds\"R\n" +
	"\vOutputEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode2d\n" +
	"\x16CodeInterpreterService\x12J\n" +
	"\aExecute\x12\x1f.codeinterpreter.ExecuteRequest\x1a\x1c.codeinterpreter.OutputEvent0\x01B+Z)microsandbox/daemon/genpb/codeinterpreterb\x06proto3"

var (
	file_codeinterpreter_codeinterpreter_proto_rawDescOnce sync.Once
	file_codeinterpreter_codeinterpreter_proto_rawDescData []byte
)

func file_codeinterpreter_codeinterpreter_proto_rawDescGZIP() []byte {
	file_codeinterpreter_codeinterpreter_proto_rawDescOnce.Do(func() {
		file_codeinterpreter_codeinterpreter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codeinterpreter_codeinterpreter_proto_rawDesc), len(file_codeinterpreter_codeinterpreter_proto_rawDesc)))
	})
	return file_codeinterpreter_codeinterpreter_proto_rawDescData
}

var file_codeinterpreter_codeinterpreter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codeinterpreter_codeinterpreter_proto_goTypes = []any{
	(*ExecuteRequest)(nil), // 0: codeinterpreter.ExecuteRequest
	(*OutputEvent)(nil),    // 1: codeinterpreter.OutputEvent
}
var file_codeinterpreter_codeinterpreter_proto_depIdxs = []int32{
	0, // 0: codeinterpreter.CodeInterpreterService.Execute:input_type -> codeinterpreter.ExecuteRequest
	1, // 1: codeinterpreter.CodeInterpreterService.Execute:output_type -> codeinterpreter.OutputEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codeinterpreter_codeinterpreter_proto_init() }
func file_codeinterpreter_codeinterpreter_proto_init() {
	if File_codeinterpreter_codeinterpreter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codeinterpreter_codeinterpreter_proto_rawDesc), len(file_codeinterpreter_codeinterpreter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codeinterpreter_codeinterpreter_proto_goTypes,
		DependencyIndexes: file_codeinterpreter_codeinterpreter_proto_depIdxs,
		MessageInfos:      file_codeinterpreter_codeinterpreter_proto_msgTypes,
	}.Build()
	File_codeinterpreter_codeinterpreter_proto = out.File
	file_codeinterpreter_codeinterpreter_proto_goTypes = nil
	file_codeinterpreter_codeinterpreter_proto_depIdxs = nil
}
