// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: templatemanager/template-manager.proto

// Package templatemanager is the gRPC contract for building custom templates. It mirrors
// E2B's TemplateService (e2b-dev/infra: packages/shared/pkg/grpc/template-manager), which
// E2B also hosts inside the orchestrator -- the builder needs the same docker + KVM +
// firecracker the VM fleet does. Stage 10 adds it: the api calls TemplateCreate to kick an
// asynchronous build and polls TemplateBuildStatus -- E2B's "accept sync, build async, poll
// status" model. See docs/STAGE10_DESIGN.md.

package templatemanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemplateService_TemplateCreate_FullMethodName      = "/templatemanager.TemplateService/TemplateCreate"
	TemplateService_TemplateBuildStatus_FullMethodName = "/templatemanager.TemplateService/TemplateBuildStatus"
)

// TemplateServiceClient is the client API for TemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TemplateService builds a named (rootfs, snapshot) image from a Dockerfile recipe.
type TemplateServiceClient interface {
	// TemplateCreate starts an asynchronous build and returns a build id immediately; the
	// build runs in the background (docker build -> build-rootfs.sh -> build-snapshot.sh).
	// Poll its progress with TemplateBuildStatus.
	TemplateCreate(ctx context.Context, in *TemplateCreateRequest, opts ...grpc.CallOption) (*TemplateCreateResponse, error)
	// TemplateBuildStatus reports a build's current state. An unknown build id is an error.
	TemplateBuildStatus(ctx context.Context, in *TemplateBuildStatusRequest, opts ...grpc.CallOption) (*TemplateBuildStatusResponse, error)
}

type templateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateServiceClient(cc grpc.ClientConnInterface) TemplateServiceClient {
	return &templateServiceClient{cc}
}

func (c *templateServiceClient) TemplateCreate(ctx context.Context, in *TemplateCreateRequest, opts ...grpc.CallOption) (*TemplateCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateCreateResponse)
	err := c.cc.Invoke(ctx, TemplateService_TemplateCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) TemplateBuildStatus(ctx context.Context, in *TemplateBuildStatusRequest, opts ...grpc.CallOption) (*TemplateBuildStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateBuildStatusResponse)
	err := c.cc.Invoke(ctx, TemplateService_TemplateBuildStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServiceServer is the server API for TemplateService service.
// All implementations must embed UnimplementedTemplateServiceServer
// for forward compatibility.
//
// TemplateService builds a named (rootfs, snapshot) image from a Dockerfile recipe.
type TemplateServiceServer interface {
	// TemplateCreate starts an asynchronous build and returns a build id immediately; the
	// build runs in the background (docker build -> build-rootfs.sh -> build-snapshot.sh).
	// Poll its progress with TemplateBuildStatus.
	TemplateCreate(context.Context, *TemplateCreateRequest) (*TemplateCreateResponse, error)
	// TemplateBuildStatus reports a build's current state. An unknown build id is an error.
	TemplateBuildStatus(context.Context, *TemplateBuildStatusRequest) (*TemplateBuildStatusResponse, error)
	mustEmbedUnimplementedTemplateServiceServer()
}

// UnimplementedTemplateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateServiceServer struct{}

func (UnimplementedTemplateServiceServer) TemplateCreate(context.Context, *TemplateCreateRequest) (*TemplateCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TemplateCreate not implemented")
}
func (UnimplementedTemplateServiceServer) TemplateBuildStatus(context.Context, *TemplateBuildStatusRequest) (*TemplateBuildStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TemplateBuildStatus not implemented")
}
func (UnimplementedTemplateServiceServer) mustEmbedUnimplementedTemplateServiceServer() {}
func (UnimplementedTemplateServiceServer) testEmbeddedByValue()                         {}

// UnsafeTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServiceServer will
// result in compilation errors.
type UnsafeTemplateServiceServer interface {
	mustEmbedUnimplementedTemplateServiceServer()
}

func RegisterTemplateServiceServer(s grpc.ServiceRegistrar, srv TemplateServiceServer) {
	// If the following call panics, it indicates UnimplementedTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateService_ServiceDesc, srv)
}

func _TemplateService_TemplateCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).TemplateCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_TemplateCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).TemplateCreate(ctx, req.(*TemplateCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_TemplateBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateBuildStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).TemplateBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_TemplateBuildStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).TemplateBuildStatus(ctx, req.(*TemplateBuildStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplateService_ServiceDesc is the grpc.ServiceDesc for TemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "templatemanager.TemplateService",
	HandlerType: (*TemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TemplateCreate",
			Handler:    _TemplateService_TemplateCreate_Handler,
		},
		{
			MethodName: "TemplateBuildStatus",
			Handler:    _TemplateService_TemplateBuildStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "templatemanager/template-manager.proto",
}
