// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: templatemanager/template-manager.proto

// Package templatemanager is the gRPC contract for building custom templates. It mirrors
// E2B's TemplateService (e2b-dev/infra: packages/shared/pkg/grpc/template-manager), which
// E2B also hosts inside the orchestrator -- the builder needs the same docker + KVM +
// firecracker the VM fleet does. Stage 10 adds it: the api calls TemplateCreate to kick an
// asynchronous build and polls TemplateBuildStatus -- E2B's "accept sync, build async, poll
// status" model. See docs/STAGE10_DESIGN.md.

package templatemanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State is the build's lifecycle: BUILDING is the initial state; it ends at SUCCESS or
// FAILED. (proto3 enums must have a zero value, which is the natural initial state here.)
type TemplateBuildStatusResponse_State int32

const (
	TemplateBuildStatusResponse_BUILDING TemplateBuildStatusResponse_State = 0
	TemplateBuildStatusResponse_SUCCESS  TemplateBuildStatusResponse_State = 1
	TemplateBuildStatusResponse_FAILED   TemplateBuildStatusResponse_State = 2
)

// Enum value maps for TemplateBuildStatusResponse_State.
var (
	TemplateBuildStatusResponse_State_name = map[int32]string{
		0: "BUILDING",
		1: "SUCCESS",
		2: "FAILED",
	}
	TemplateBuildStatusResponse_State_value = map[string]int32{
		"BUILDING": 0,
		"SUCCESS":  1,
		"FAILED":   2,
	}
)

func (x TemplateBuildStatusResponse_State) Enum() *TemplateBuildStatusResponse_State {
	p := new(TemplateBuildStatusResponse_State)
	*p = x
	return p
}

func (x TemplateBuildStatusResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateBuildStatusResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_templatemanager_template_manager_proto_enumTypes[0].Descriptor()
}

func (TemplateBuildStatusResponse_State) Type() protoreflect.EnumType {
	return &file_templatemanager_template_manager_proto_enumTypes[0]
}

func (x TemplateBuildStatusResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateBuildStatusResponse_State.Descriptor instead.
func (TemplateBuildStatusResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_templatemanager_template_manager_proto_rawDescGZIP(), []int{3, 0}
}

// TemplateCreateRequest is the recipe to build. The field numbers are the wire identity --
// never change or reuse one once shipped (see orchestrator.proto for the why).
type TemplateCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                      // template name (validated; "default" is rejected -- it is the stock image)
	Dockerfile    string                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`                          // the recipe contents (FROM microsandbox-agent + RUN ...)
	WithSnapshot  bool                   `protobuf:"varint,3,opt,name=with_snapshot,json=withSnapshot,proto3" json:"with_snapshot,omitempty"` // also build the warm snapshot (for from_snapshot starts)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateCreateRequest) Reset() {
	*x = TemplateCreateRequest{}
	mi := &file_templatemanager_template_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateCreateRequest) ProtoMessage() {}

func (x *TemplateCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_templatemanager_template_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateCreateRequest.ProtoReflect.Descriptor instead.
func (*TemplateCreateRequest) Descriptor() ([]byte, []int) {
	return file_templatemanager_template_manager_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateCreateRequest) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

func (x *TemplateCreateRequest) GetWithSnapshot() bool {
	if x != nil {
		return x.WithSnapshot
	}
	return false
}

type TemplateCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateCreateResponse) Reset() {
	*x = TemplateCreateResponse{}
	mi := &file_templatemanager_template_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateCreateResponse) ProtoMessage() {}

func (x *TemplateCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_templatemanager_template_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateCreateResponse.ProtoReflect.Descriptor instead.
func (*TemplateCreateResponse) Descriptor() ([]byte, []int) {
	return file_templatemanager_template_manager_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateCreateResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type TemplateBuildStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateBuildStatusRequest) Reset() {
	*x = TemplateBuildStatusRequest{}
	mi := &file_templatemanager_template_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildStatusRequest) ProtoMessage() {}

func (x *TemplateBuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_templatemanager_template_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildStatusRequest.ProtoReflect.Descriptor instead.
func (*TemplateBuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_templatemanager_template_manager_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateBuildStatusRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type TemplateBuildStatusResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	State         TemplateBuildStatusResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=templatemanager.TemplateBuildStatusResponse_State" json:"state,omitempty"`
	Detail        string                            `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // last log line / error message (empty while building cleanly)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateBuildStatusResponse) Reset() {
	*x = TemplateBuildStatusResponse{}
	mi := &file_templatemanager_template_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildStatusResponse) ProtoMessage() {}

func (x *TemplateBuildStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_templatemanager_template_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildStatusResponse.ProtoReflect.Descriptor instead.
func (*TemplateBuildStatusResponse) Descriptor() ([]byte, []int) {
	return file_templatemanager_template_manager_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateBuildStatusResponse) GetState() TemplateBuildStatusResponse_State {
	if x != nil {
		return x.State
	}
	return TemplateBuildStatusResponse_BUILDING
}

func (x *TemplateBuildStatusResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_templatemanager_template_manager_proto protoreflect.FileDescriptor

const file_templatemanager_template_manager_proto_rawDesc = "" +
	"\n" +
	"&templatemanager/template-manager.proto\x12\x0ftemplatemanager\"p\n" +
	"\x15TemplateCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tR\n" +
	"dockerfile\x12#\n" +
	"\rwith_snapshot\x18\x03 \x01(\bR\fwithSnapshot\"3\n" +
	"\x16TemplateCreateResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"7\n" +
	"\x1aTemplateBuildStatusRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"\xaf\x01\n" +
	"\x1bTemplateBuildStatusResponse\x12H\n" +
	"\x05state\x18\x01 \x01(\x0e22.templatemanager.TemplateBuildStatusResponse.StateR\x05state\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\".\n" +
	"\x05State\x12\f\n" +
	"\bBUILDING\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x022\xe6\x01\n" +
	"\x0fTemplateService\x12a\n" +
	"\x0eTemplateCreate\x12&.templatemanager.TemplateCreateRequest\x1a'.templatemanager.TemplateCreateResponse\x12p\n" +
	"\x13TemplateBuildStatus\x12+.templatemanager.TemplateBuildStatusRequest\x1a,.templatemanager.TemplateBuildStatusResponseB0Z.microsandbox/services/pkg/grpc/templatemanagerb\x06proto3"

var (
	file_templatemanager_template_manager_proto_rawDescOnce sync.Once
	file_templatemanager_template_manager_proto_rawDescData []byte
)

func file_templatemanager_template_manager_proto_rawDescGZIP() []byte {
	file_templatemanager_template_manager_proto_rawDescOnce.Do(func() {
		file_templatemanager_template_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_templatemanager_template_manager_proto_rawDesc), len(file_templatemanager_template_manager_proto_rawDesc)))
	})
	return file_templatemanager_template_manager_proto_rawDescData
}

var file_templatemanager_template_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_templatemanager_template_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_templatemanager_template_manager_proto_goTypes = []any{
	(TemplateBuildStatusResponse_State)(0), // 0: templatemanager.TemplateBuildStatusResponse.State
	(*TemplateCreateRequest)(nil),          // 1: templatemanager.TemplateCreateRequest
	(*TemplateCreateResponse)(nil),         // 2: templatemanager.TemplateCreateResponse
	(*TemplateBuildStatusRequest)(nil),     // 3: templatemanager.TemplateBuildStatusRequest
	(*TemplateBuildStatusResponse)(nil),    // 4: templatemanager.TemplateBuildStatusResponse
}
var file_templatemanager_template_manager_proto_depIdxs = []int32{
	0, // 0: templatemanager.TemplateBuildStatusResponse.state:type_name -> templatemanager.TemplateBuildStatusResponse.State
	1, // 1: templatemanager.TemplateService.TemplateCreate:input_type -> templatemanager.TemplateCreateRequest
	3, // 2: templatemanager.TemplateService.TemplateBuildStatus:input_type -> templatemanager.TemplateBuildStatusRequest
	2, // 3: templatemanager.TemplateService.TemplateCreate:output_type -> templatemanager.TemplateCreateResponse
	4, // 4: templatemanager.TemplateService.TemplateBuildStatus:output_type -> templatemanager.TemplateBuildStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_templatemanager_template_manager_proto_init() }
func file_templatemanager_template_manager_proto_init() {
	if File_templatemanager_template_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_templatemanager_template_manager_proto_rawDesc), len(file_templatemanager_template_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_templatemanager_template_manager_proto_goTypes,
		DependencyIndexes: file_templatemanager_template_manager_proto_depIdxs,
		EnumInfos:         file_templatemanager_template_manager_proto_enumTypes,
		MessageInfos:      file_templatemanager_template_manager_proto_msgTypes,
	}.Build()
	File_templatemanager_template_manager_proto = out.File
	file_templatemanager_template_manager_proto_goTypes = nil
	file_templatemanager_template_manager_proto_depIdxs = nil
}
