// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: envd/envd.proto

// Package envd is the in-VM daemon's ConnectRPC contract (Stage 11), matching E2B's envd:
// a Filesystem service and a Process service. It replaces the hand-rolled HTTP/JSON
// endpoints (/files/*, /commands) the Stage-7 daemon served; the message shapes mirror that
// JSON exactly, so behavior is unchanged -- only the framing (Connect over HTTP/1.1) moves.
// The stateful Python kernel (/execute) lives in a separate code-interpreter service.
// See docs/STAGE11_DESIGN.md.
package envdconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	envd "microsandbox/daemon/genpb/envd"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FilesystemServiceName is the fully-qualified name of the FilesystemService service.
	FilesystemServiceName = "envd.FilesystemService"
	// ProcessServiceName is the fully-qualified name of the ProcessService service.
	ProcessServiceName = "envd.ProcessService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FilesystemServiceReadProcedure is the fully-qualified name of the FilesystemService's Read RPC.
	FilesystemServiceReadProcedure = "/envd.FilesystemService/Read"
	// FilesystemServiceWriteProcedure is the fully-qualified name of the FilesystemService's Write RPC.
	FilesystemServiceWriteProcedure = "/envd.FilesystemService/Write"
	// FilesystemServiceListProcedure is the fully-qualified name of the FilesystemService's List RPC.
	FilesystemServiceListProcedure = "/envd.FilesystemService/List"
	// ProcessServiceRunProcedure is the fully-qualified name of the ProcessService's Run RPC.
	ProcessServiceRunProcedure = "/envd.ProcessService/Run"
)

// FilesystemServiceClient is a client for the envd.FilesystemService service.
type FilesystemServiceClient interface {
	Read(context.Context, *connect.Request[envd.ReadRequest]) (*connect.Response[envd.ReadResponse], error)
	Write(context.Context, *connect.Request[envd.WriteRequest]) (*connect.Response[envd.WriteResponse], error)
	List(context.Context, *connect.Request[envd.ListRequest]) (*connect.Response[envd.ListResponse], error)
}

// NewFilesystemServiceClient constructs a client for the envd.FilesystemService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFilesystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FilesystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	filesystemServiceMethods := envd.File_envd_envd_proto.Services().ByName("FilesystemService").Methods()
	return &filesystemServiceClient{
		read: connect.NewClient[envd.ReadRequest, envd.ReadResponse](
			httpClient,
			baseURL+FilesystemServiceReadProcedure,
			connect.WithSchema(filesystemServiceMethods.ByName("Read")),
			connect.WithClientOptions(opts...),
		),
		write: connect.NewClient[envd.WriteRequest, envd.WriteResponse](
			httpClient,
			baseURL+FilesystemServiceWriteProcedure,
			connect.WithSchema(filesystemServiceMethods.ByName("Write")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[envd.ListRequest, envd.ListResponse](
			httpClient,
			baseURL+FilesystemServiceListProcedure,
			connect.WithSchema(filesystemServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// filesystemServiceClient implements FilesystemServiceClient.
type filesystemServiceClient struct {
	read  *connect.Client[envd.ReadRequest, envd.ReadResponse]
	write *connect.Client[envd.WriteRequest, envd.WriteResponse]
	list  *connect.Client[envd.ListRequest, envd.ListResponse]
}

// Read calls envd.FilesystemService.Read.
func (c *filesystemServiceClient) Read(ctx context.Context, req *connect.Request[envd.ReadRequest]) (*connect.Response[envd.ReadResponse], error) {
	return c.read.CallUnary(ctx, req)
}

// Write calls envd.FilesystemService.Write.
func (c *filesystemServiceClient) Write(ctx context.Context, req *connect.Request[envd.WriteRequest]) (*connect.Response[envd.WriteResponse], error) {
	return c.write.CallUnary(ctx, req)
}

// List calls envd.FilesystemService.List.
func (c *filesystemServiceClient) List(ctx context.Context, req *connect.Request[envd.ListRequest]) (*connect.Response[envd.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// FilesystemServiceHandler is an implementation of the envd.FilesystemService service.
type FilesystemServiceHandler interface {
	Read(context.Context, *connect.Request[envd.ReadRequest]) (*connect.Response[envd.ReadResponse], error)
	Write(context.Context, *connect.Request[envd.WriteRequest]) (*connect.Response[envd.WriteResponse], error)
	List(context.Context, *connect.Request[envd.ListRequest]) (*connect.Response[envd.ListResponse], error)
}

// NewFilesystemServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFilesystemServiceHandler(svc FilesystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	filesystemServiceMethods := envd.File_envd_envd_proto.Services().ByName("FilesystemService").Methods()
	filesystemServiceReadHandler := connect.NewUnaryHandler(
		FilesystemServiceReadProcedure,
		svc.Read,
		connect.WithSchema(filesystemServiceMethods.ByName("Read")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemServiceWriteHandler := connect.NewUnaryHandler(
		FilesystemServiceWriteProcedure,
		svc.Write,
		connect.WithSchema(filesystemServiceMethods.ByName("Write")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemServiceListHandler := connect.NewUnaryHandler(
		FilesystemServiceListProcedure,
		svc.List,
		connect.WithSchema(filesystemServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/envd.FilesystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FilesystemServiceReadProcedure:
			filesystemServiceReadHandler.ServeHTTP(w, r)
		case FilesystemServiceWriteProcedure:
			filesystemServiceWriteHandler.ServeHTTP(w, r)
		case FilesystemServiceListProcedure:
			filesystemServiceListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFilesystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFilesystemServiceHandler struct{}

func (UnimplementedFilesystemServiceHandler) Read(context.Context, *connect.Request[envd.ReadRequest]) (*connect.Response[envd.ReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("envd.FilesystemService.Read is not implemented"))
}

func (UnimplementedFilesystemServiceHandler) Write(context.Context, *connect.Request[envd.WriteRequest]) (*connect.Response[envd.WriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("envd.FilesystemService.Write is not implemented"))
}

func (UnimplementedFilesystemServiceHandler) List(context.Context, *connect.Request[envd.ListRequest]) (*connect.Response[envd.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("envd.FilesystemService.List is not implemented"))
}

// ProcessServiceClient is a client for the envd.ProcessService service.
type ProcessServiceClient interface {
	Run(context.Context, *connect.Request[envd.RunRequest]) (*connect.Response[envd.RunResponse], error)
}

// NewProcessServiceClient constructs a client for the envd.ProcessService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProcessServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProcessServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	processServiceMethods := envd.File_envd_envd_proto.Services().ByName("ProcessService").Methods()
	return &processServiceClient{
		run: connect.NewClient[envd.RunRequest, envd.RunResponse](
			httpClient,
			baseURL+ProcessServiceRunProcedure,
			connect.WithSchema(processServiceMethods.ByName("Run")),
			connect.WithClientOptions(opts...),
		),
	}
}

// processServiceClient implements ProcessServiceClient.
type processServiceClient struct {
	run *connect.Client[envd.RunRequest, envd.RunResponse]
}

// Run calls envd.ProcessService.Run.
func (c *processServiceClient) Run(ctx context.Context, req *connect.Request[envd.RunRequest]) (*connect.Response[envd.RunResponse], error) {
	return c.run.CallUnary(ctx, req)
}

// ProcessServiceHandler is an implementation of the envd.ProcessService service.
type ProcessServiceHandler interface {
	Run(context.Context, *connect.Request[envd.RunRequest]) (*connect.Response[envd.RunResponse], error)
}

// NewProcessServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProcessServiceHandler(svc ProcessServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	processServiceMethods := envd.File_envd_envd_proto.Services().ByName("ProcessService").Methods()
	processServiceRunHandler := connect.NewUnaryHandler(
		ProcessServiceRunProcedure,
		svc.Run,
		connect.WithSchema(processServiceMethods.ByName("Run")),
		connect.WithHandlerOptions(opts...),
	)
	return "/envd.ProcessService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProcessServiceRunProcedure:
			processServiceRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProcessServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProcessServiceHandler struct{}

func (UnimplementedProcessServiceHandler) Run(context.Context, *connect.Request[envd.RunRequest]) (*connect.Response[envd.RunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("envd.ProcessService.Run is not implemented"))
}
