// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: codeinterpreter/codeinterpreter.proto

// Package codeinterpreter is the ConnectRPC contract for running code in the stateful
// Python kernel (Stage 11), matching E2B's separate code-interpreter service. Execute is
// server-streaming: it streams OutputEvents (stdout / stderr / error / end) as the cell
// runs -- the Connect-over-HTTP/1.1 equivalent of the Stage-7 daemon's /execute SSE.
// Implemented in 11b (the kernel moves here onto its own vsock port). See docs/STAGE11_DESIGN.md.
package codeinterpreterconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	codeinterpreter "microsandbox/daemon/genpb/codeinterpreter"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CodeInterpreterServiceName is the fully-qualified name of the CodeInterpreterService service.
	CodeInterpreterServiceName = "codeinterpreter.CodeInterpreterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CodeInterpreterServiceExecuteProcedure is the fully-qualified name of the
	// CodeInterpreterService's Execute RPC.
	CodeInterpreterServiceExecuteProcedure = "/codeinterpreter.CodeInterpreterService/Execute"
)

// CodeInterpreterServiceClient is a client for the codeinterpreter.CodeInterpreterService service.
type CodeInterpreterServiceClient interface {
	Execute(context.Context, *connect.Request[codeinterpreter.ExecuteRequest]) (*connect.ServerStreamForClient[codeinterpreter.OutputEvent], error)
}

// NewCodeInterpreterServiceClient constructs a client for the
// codeinterpreter.CodeInterpreterService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCodeInterpreterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CodeInterpreterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	codeInterpreterServiceMethods := codeinterpreter.File_codeinterpreter_codeinterpreter_proto.Services().ByName("CodeInterpreterService").Methods()
	return &codeInterpreterServiceClient{
		execute: connect.NewClient[codeinterpreter.ExecuteRequest, codeinterpreter.OutputEvent](
			httpClient,
			baseURL+CodeInterpreterServiceExecuteProcedure,
			connect.WithSchema(codeInterpreterServiceMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
	}
}

// codeInterpreterServiceClient implements CodeInterpreterServiceClient.
type codeInterpreterServiceClient struct {
	execute *connect.Client[codeinterpreter.ExecuteRequest, codeinterpreter.OutputEvent]
}

// Execute calls codeinterpreter.CodeInterpreterService.Execute.
func (c *codeInterpreterServiceClient) Execute(ctx context.Context, req *connect.Request[codeinterpreter.ExecuteRequest]) (*connect.ServerStreamForClient[codeinterpreter.OutputEvent], error) {
	return c.execute.CallServerStream(ctx, req)
}

// CodeInterpreterServiceHandler is an implementation of the codeinterpreter.CodeInterpreterService
// service.
type CodeInterpreterServiceHandler interface {
	Execute(context.Context, *connect.Request[codeinterpreter.ExecuteRequest], *connect.ServerStream[codeinterpreter.OutputEvent]) error
}

// NewCodeInterpreterServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCodeInterpreterServiceHandler(svc CodeInterpreterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	codeInterpreterServiceMethods := codeinterpreter.File_codeinterpreter_codeinterpreter_proto.Services().ByName("CodeInterpreterService").Methods()
	codeInterpreterServiceExecuteHandler := connect.NewServerStreamHandler(
		CodeInterpreterServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(codeInterpreterServiceMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	return "/codeinterpreter.CodeInterpreterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CodeInterpreterServiceExecuteProcedure:
			codeInterpreterServiceExecuteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCodeInterpreterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCodeInterpreterServiceHandler struct{}

func (UnimplementedCodeInterpreterServiceHandler) Execute(context.Context, *connect.Request[codeinterpreter.ExecuteRequest], *connect.ServerStream[codeinterpreter.OutputEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("codeinterpreter.CodeInterpreterService.Execute is not implemented"))
}
