"""Client SDK -- the interface users actually face when writing code.

Design goal: keep the feel as close to E2B as possible. Typical usage:

    from microsandbox import Sandbox

    with Sandbox() as sandbox:
        execution = sandbox.run_code("print('hello from sandbox')")
        print(execution.stdout)

Every Sandbox is a **Firecracker microVM**: an independent guest kernel behind
the KVM hardware-virtualization boundary (the strongest isolation in this
project), with the control channel carried over **vsock** and a stateful Jupyter
kernel running inside the VM (variables persist across run_code, like E2B).
Prepare the vendor/ artifacts first (firecracker binary + guest kernel + rootfs):
see docs/MICROVM_DESIGN.md §7 and scripts/build-rootfs.sh.

History: this project grew stage by stage (host subprocess -> Docker container ->
resident container -> microVM). Those earlier isolation backends were learning
scaffolding; now that the microVM works they have been removed, leaving only the
Firecracker path. The staged journey is preserved in the git history.
"""

from __future__ import annotations

import json
import os
import pathlib
import shutil
import socket
import subprocess
import tempfile
import time
from collections.abc import Callable, Iterator
from typing import Any

from .protocol import EventType, Execution, ExecuteRequest, OutputEvent

# ---- Firecracker microVM topology ----
# The client hand-creates and owns the isolation environment (a microVM); the
# daemon resides inside the VM, exposed via vsock. The artifacts (firecracker
# binary / kernel / rootfs) are generated by scripts/build-rootfs.sh under the
# repo's vendor/ (see docs/MICROVM_DESIGN.md §7).
_MICROVM_VSOCK_PORT = 1024   # vsock port the daemon listens on inside the VM (matches the rootfs's /init)
_MICROVM_GUEST_CID = 3       # guest's vsock CID (host is fixed at 2)
_MICROVM_VCPUS = 1
_MICROVM_MEM_MIB = 512       # a Jupyter kernel runs inside the VM; 256 is tight, so give 512


def _vendor_dir() -> pathlib.Path:
    """Artifacts directory: client.py is under src/microsandbox/, so the repo root is parents[2]."""
    return pathlib.Path(__file__).resolve().parents[2] / "vendor"


def _firecracker_api(
    sock_path: str, method: str, path: str, body: dict, timeout: float = 15.0
) -> int:
    """Send one request to Firecracker's REST API (HTTP over AF_UNIX), returning the status code.

    Operations like snapshot load/create can't be expressed via --config-file, so they
    must go through the API. api.sock may not yet have been created by firecracker, so
    poll and retry until timeout when the connection fails. Only the status line is read
    (the body is ignored).
    """
    payload = json.dumps(body).encode()
    head = (
        f"{method} {path} HTTP/1.1\r\nHost: localhost\r\n"
        f"Content-Type: application/json\r\nContent-Length: {len(payload)}\r\n"
        f"Connection: close\r\n\r\n"
    ).encode()
    deadline = time.time() + timeout
    while True:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.settimeout(2)
        try:
            sock.connect(sock_path)
        except OSError:
            sock.close()
            if time.time() > deadline:
                raise
            time.sleep(0.005)
            continue
        try:
            sock.sendall(head + payload)
            return int(sock.makefile("rb").readline().split(b" ")[1])
        finally:
            sock.close()


# ---- vsock transport ----
#
# The control channel between the client and the in-VM daemon is HTTP/SSE carried
# over vsock. Firecracker multiplexes the guest's vsock onto a single Unix domain
# socket (UDS) on the host; after a text handshake (CONNECT <port> -> OK <hostport>)
# the byte stream is wired through to the daemon listening on that vsock port inside
# the guest, and from then on both sides speak the same HTTP/SSE. The protocol bytes
# (protocol.py) are byte-for-byte what earlier stages carried over TCP -- only the
# underlying pipe is vsock now. urllib can't do this CONNECT handshake, so we
# hand-write a minimal HTTP/1.1 client over the raw socket.


class _Response:
    """The normalized result of one HTTP round-trip over vsock: a status code + a file-like.

    Two usages share it; the only difference is how the caller reads fp:
      - streaming (SSE): `for line in resp:` consumes line by line until the connection
        closes (EOF);
      - single-shot (JSON): `resp.read()` reads the whole body at once.
    fp is the vsock socket's read file, which supports both "line-by-line iteration" and
    read(), so the upper-level run_code / files / commands logic doesn't care that the
    transport underneath is vsock.
    """

    def __init__(
        self, status: int, fp: Any, on_close: Callable[[], None] | None = None
    ) -> None:
        self.status = status
        self.fp = fp
        self._on_close = on_close

    def __iter__(self) -> Iterator[bytes]:
        return iter(self.fp)

    def read(self) -> bytes:
        return self.fp.read()

    def close(self) -> None:
        try:
            self.fp.close()
        finally:
            if self._on_close is not None:
                self._on_close()

    def __enter__(self) -> "_Response":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class _VsockTransport:
    """HTTP over vsock: the microVM control channel.

    Firecracker multiplexes the guest's vsock onto a single Unix domain socket (UDS) on
    the host. The handshake is a text protocol: after connecting to the UDS, send
    `CONNECT <port>\\n`, Firecracker replies `OK <hostport>\\n`, and from then on this
    byte stream is wired to the daemon listening on that vsock port inside the guest.
    Once the handshake is done, both sides speak the same HTTP/SSE -- so here we only
    need to hand-write a minimal HTTP/1.1 client over the raw socket.
    """

    def __init__(self, uds_path: str, vsock_port: int) -> None:
        self._uds = uds_path
        self._vsock_port = vsock_port

    def request(
        self,
        method: str,
        path: str,
        body: bytes | None = None,
        headers: dict[str, str] | None = None,
        timeout: float | None = None,
    ) -> _Response:
        """Send one HTTP request over vsock, returning a _Response. timeout=None means no timeout (blocking)."""
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.settimeout(timeout)  # None=blocking (used by streaming /execute); health check passes 1s
        try:
            sock.connect(self._uds)
            # 1. Firecracker vsock handshake: CONNECT <port> -> OK <hostport>
            sock.sendall(f"CONNECT {self._vsock_port}\n".encode())
            rfile = sock.makefile("rb")  # reading the response goes through it; writes always use sock.sendall, to avoid read/write buffers interfering
            ack = rfile.readline()
            if not ack.startswith(b"OK"):
                # e.g. nobody is listening on that vsock port inside the guest, so Firecracker replies non-OK.
                raise ConnectionError(f"vsock CONNECT rejected: {ack!r}")
            # 2. Hand-write the minimal HTTP/1.1 request line + headers + body
            head = [f"{method} {path} HTTP/1.1", "Host: sandbox", "Connection: close"]
            hdrs = dict(headers or {})
            if body is not None:
                hdrs.setdefault("Content-Length", str(len(body)))
            head += [f"{k}: {v}" for k, v in hdrs.items()]
            sock.sendall(("\r\n".join(head) + "\r\n\r\n").encode())
            if body:
                sock.sendall(body)
            # 3. Read the status line + skip the response headers, leaving rfile at the start of the body for the upper layer (both streaming and single-shot read from here)
            status_line = rfile.readline().decode("latin-1")
            status = int(status_line.split(" ", 2)[1])
            while True:
                line = rfile.readline()
                if line in (b"\r\n", b"\n", b""):
                    break
            return _Response(status, rfile, on_close=sock.close)
        except Exception:
            sock.close()
            raise


class Sandbox:
    """A client handle for a sandbox session, backed by a Firecracker microVM.

    Args:
        timeout_seconds: per-execution timeout passed to the daemon.
        from_snapshot: if True, restore from a pre-warmed snapshot in milliseconds
            (skipping kernel boot + Jupyter kernel cold start, ~30ms to ready vs ~0.94s
            cold start). Run scripts/build-snapshot.sh first; currently single-instance
            (the snapshot's vsock uds path is fixed, see docs/MICROVM_DESIGN.md §8).

    On construction the client starts (or restores) the microVM, connects in over vsock,
    and waits for the in-VM daemon to become healthy; close() (or leaving the `with`
    block) kills the firecracker process and cleans up the working directory.
    """

    def __init__(
        self,
        timeout_seconds: float = 30.0,
        from_snapshot: bool = False,
    ) -> None:
        self.timeout_seconds = timeout_seconds
        self._from_snapshot = from_snapshot
        self._proc: subprocess.Popen | None = None     # the firecracker process (= the VM)
        self._transport: _VsockTransport | None = None  # set by _spawn_microvm / _restore_microvm
        self._workdir: pathlib.Path | None = None       # per-VM working directory (config / vsock UDS / api sock / console.log)
        self._console_log: pathlib.Path | None = None   # firecracker/guest serial log (for diagnostics)

        # File / shell namespaces, with a feel aligned to E2B's sandbox.files /
        # sandbox.commands. They only use the transport when called, so building them here is enough.
        self.files = _Files(self)
        self.commands = _Commands(self)

        # Safety-net: after _spawn_*/_restore_* succeeds the VM is already up; if the
        # immediately following health check fails (the daemon won't start / is too slow),
        # the exception propagates out of __init__ -- at which point the `with` statement
        # hasn't entered __enter__, __exit__ never fires, and the already-started
        # firecracker process would leak. So here we close it ourselves and re-raise
        # (close is idempotent, so it's safe).
        try:
            if from_snapshot:
                self._restore_microvm()
            else:
                self._spawn_microvm()
            self._wait_until_healthy()
        except Exception:
            self.close()
            raise

    # ----- lifecycle -----

    def _spawn_microvm(self) -> None:
        """Start a Firecracker microVM with the daemon running inside, exposed via vsock.

        The client owns the isolation environment's lifecycle: it writes a declarative
        config, starts firecracker, and connects in over vsock. The daemon (server.py) and
        the protocol (protocol.py) don't know they're inside a VM -- switching isolation =
        switching the client's creation logic + the transport, with the protocol untouched.
        """
        vendor = _vendor_dir()
        fc_bin, kernel, rootfs = (
            vendor / "firecracker", vendor / "vmlinux", vendor / "rootfs.ext4")

        problem = self._check_microvm_available(fc_bin, kernel, rootfs)
        if problem:
            raise RuntimeError(f"Failed to create microVM: {problem}")

        # per-VM working directory: config, vsock UDS, api sock, console.log all go here (the whole thing is deleted on close).
        self._workdir = pathlib.Path(tempfile.mkdtemp(prefix="microsandbox-vm-"))
        uds = self._workdir / "fc.vsock"
        self._console_log = self._workdir / "console.log"

        # A single JSON declares the entire VM (during the learning phase, use
        # --config-file rather than per-item REST, for easy at-a-glance reading).
        config = {
            "boot-source": {
                "kernel_image_path": str(kernel),
                # root=/dev/vda read-only root; init=/init runs our minimal PID 1 (which execs the daemon).
                "boot_args": (
                    "console=ttyS0 reboot=k panic=1 pci=off "
                    "root=/dev/vda ro init=/init"
                ),
            },
            "drives": [{
                "drive_id": "rootfs",
                "path_on_host": str(rootfs),
                "is_root_device": True,
                "is_read_only": True,   # read-only root; all writes go to the in-VM tmpfs /tmp
            }],
            "machine-config": {
                "vcpu_count": _MICROVM_VCPUS, "mem_size_mib": _MICROVM_MEM_MIB},
            # Firecracker multiplexes the guest vsock onto this UDS; the client's _VsockTransport connects to it.
            "vsock": {"guest_cid": _MICROVM_GUEST_CID, "uds_path": str(uds)},
        }
        config_path = self._workdir / "config.json"
        config_path.write_text(json.dumps(config))

        # firecracker's stdout/stderr (including the guest serial console) lands in a file
        # -- can't use PIPE: the guest console writes continuously, and a full PIPE buffer
        # would stall the VM. Read this file to diagnose startup failures.
        with open(self._console_log, "wb") as log_fh:
            self._proc = subprocess.Popen(
                [str(fc_bin), "--api-sock", str(self._workdir / "api.sock"),
                 "--config-file", str(config_path)],
                stdout=log_fh, stderr=subprocess.STDOUT,
            )
        # The daemon listens on vsock 1024 inside the VM; the host connects in via the uds.
        # The health check fires next in __init__, going through exactly this vsock transport.
        self._transport = _VsockTransport(str(uds), _MICROVM_VSOCK_PORT)

    @staticmethod
    def _check_microvm_available(
        fc_bin: pathlib.Path, kernel: pathlib.Path, rootfs: pathlib.Path
    ) -> str | None:
        """Surface environment problems before startup with actionable guidance."""
        if not fc_bin.exists():
            return f"Missing firecracker binary ({fc_bin}); see docs/MICROVM_DESIGN.md §7 for setup"
        if not kernel.exists():
            return f"Missing kernel vmlinux ({kernel}); see docs/MICROVM_DESIGN.md §7 for setup"
        if not rootfs.exists():
            return f"Missing rootfs ({rootfs}); please run scripts/build-rootfs.sh first"
        if not os.path.exists("/dev/kvm"):
            return "/dev/kvm does not exist: (nested) hardware virtualization is not enabled on this machine"
        if not os.access("/dev/kvm", os.R_OK | os.W_OK):
            return ("No permission to access /dev/kvm: add the current user to the kvm group"
                    " (sudo usermod -aG kvm $USER) and restart WSL")
        return None

    def _microvm_log(self) -> str:
        """Grab the tail of the microVM's firecracker/guest serial log, only for startup-failure diagnostics."""
        if self._console_log is None:
            return ""
        try:
            return self._console_log.read_text(errors="replace")[-1500:].strip()
        except OSError:
            return ""

    def _restore_microvm(self) -> None:
        """Restore a microVM from a pre-generated snapshot -- skipping kernel boot and
        Jupyter kernel cold start, achieving millisecond-level readiness (cf. _spawn_microvm
        cold start ~0.94s, restore-to-ready ~30ms).

        Mechanism: a snapshot contains two artifacts -- vmstate (device/CPU state) +
        memfile (guest memory, already containing a hot kernel). Start an empty firecracker,
        pour the state back via the REST API `PUT /snapshot/load` + resume, and the VM
        continues running from its frozen point, with both the daemon and kernel already
        ready. Note rootfs.ext4 must still be at its original path (the snapshot stores only
        memory/device state; disk contents are still provided by the host's backing file).

        Known limitation (single-instance): the vsock uds path in the snapshot is fixed
        (vendor/snapshot/fc.vsock), so only one can be restored at a time. Concurrent restore
        + a pre-warm pool require a per-VM uds override (a future enhancement).
        """
        vendor = _vendor_dir()
        snap = vendor / "snapshot"
        vmstate, memfile, uds = snap / "vmstate", snap / "memfile", snap / "fc.vsock"

        problem = self._check_microvm_available(
            vendor / "firecracker", vendor / "vmlinux", vendor / "rootfs.ext4")
        if problem:
            raise RuntimeError(f"Failed to restore microVM: {problem}")
        if not vmstate.exists() or not memfile.exists():
            raise RuntimeError(f"Missing snapshot ({snap}); please run scripts/build-snapshot.sh first")

        self._workdir = pathlib.Path(tempfile.mkdtemp(prefix="microsandbox-vm-"))
        self._console_log = self._workdir / "console.log"
        api_sock = self._workdir / "api.sock"
        uds.unlink(missing_ok=True)  # clear out the same-named socket left from last time; firecracker will re-listen on this fixed path

        with open(self._console_log, "wb") as log_fh:
            self._proc = subprocess.Popen(
                [str(vendor / "firecracker"), "--api-sock", str(api_sock)],
                stdout=log_fh, stderr=subprocess.STDOUT,
            )
        status = _firecracker_api(str(api_sock), "PUT", "/snapshot/load", {
            "snapshot_path": str(vmstate),
            "mem_backend": {"backend_type": "File", "backend_path": str(memfile)},
            "resume_vm": True,
        })
        if status not in (200, 204):
            raise RuntimeError(
                f"snapshot/load failed: HTTP {status}; {self._microvm_log()[-300:]}")
        self._transport = _VsockTransport(str(uds), _MICROVM_VSOCK_PORT)

    def _ensure_transport(self) -> _VsockTransport:
        """Return the vsock transport, set by _spawn_microvm / _restore_microvm during construction."""
        assert self._transport is not None, "transport not initialized (did the microVM fail to start?)"
        return self._transport

    def _wait_until_healthy(self, attempts: int = 50, delay: float = 0.1) -> None:
        transport = self._ensure_transport()
        for _ in range(attempts):
            # If the firecracker process has already exited, don't keep polling for 5
            # seconds -- read the guest serial log as the error instead (e.g. the in-VM
            # daemon hit a python import error, PID 1 exited, the kernel panicked, and
            # firecracker exited; the traceback is in console.log).
            if self._proc is not None and self._proc.poll() is not None:
                detail = self._microvm_log()
                raise RuntimeError(
                    f"sandbox microVM exited at startup: {detail[-500:] or '(no console log)'}"
                )
            try:
                with transport.request("GET", "/health", timeout=1) as resp:
                    if resp.status == 200:
                        return
            except Exception:
                time.sleep(delay)
        # Not ready within the time limit: append the serial-log tail for easier troubleshooting.
        detail = self._microvm_log()
        raise RuntimeError(
            "sandbox microVM did not become healthy in time"
            + (f": {detail[-500:]}" if detail else "")
        )

    def close(self) -> None:
        if self._proc is not None:
            # Killing the firecracker process destroys the entire VM (its memory + device
            # state vanish with the process) -- much cleaner than tearing down a container.
            self._proc.terminate()
            try:
                self._proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._proc.kill()
            self._proc = None
        if self._workdir is not None:
            # Clean up the per-VM working directory (config / vsock UDS / api sock /
            # console.log are all inside). ignore_errors is an idempotent safety-net.
            shutil.rmtree(self._workdir, ignore_errors=True)
            self._workdir = None

    def __enter__(self) -> "Sandbox":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()

    # ----- core API -----

    def run_code(
        self,
        code: str,
        language: str = "python",
        on_stdout: Callable[[str], None] | None = None,
        on_stderr: Callable[[str], None] | None = None,
    ) -> Execution:
        """Execute a piece of code, returning the aggregated Execution result.

        Optionally pass on_stdout / on_stderr callbacks to get streaming output in real
        time (e.g. print as it runs), while still ultimately returning the complete
        Execution.
        """
        execution = Execution()
        for event in self._stream(code, language):
            execution.events.append(event)
            if event.type == EventType.STDOUT:
                execution.stdout += event.data
                if on_stdout:
                    on_stdout(event.data)
            elif event.type == EventType.STDERR:
                execution.stderr += event.data
                if on_stderr:
                    on_stderr(event.data)
            elif event.type == EventType.ERROR:
                execution.error = (execution.error or "") + event.data
            elif event.type == EventType.END:
                execution.exit_code = event.exit_code
        return execution

    def _stream(self, code: str, language: str) -> Iterator[OutputEvent]:
        """Issue an execution request to the in-VM daemon, parsing the SSE stream line by line.

        The request travels over vsock; here we only translate /execute's SSE response back
        into OutputEvents line by line.
        """
        request = ExecuteRequest(
            code=code, language=language, timeout_seconds=self.timeout_seconds
        )
        with self._ensure_transport().request(
            "POST",
            "/execute",
            body=request.to_json().encode(),
            headers={"Content-Type": "application/json"},
        ) as resp:
            for raw in resp:
                line = raw.decode(errors="replace").rstrip("\n")
                if not line.startswith("data: "):
                    continue
                payload = line[len("data: "):]
                if not payload:
                    continue
                yield OutputEvent.from_sse_payload(payload)

    def _post_json(self, path: str, payload: dict) -> dict:
        """POST a JSON to a non-streaming endpoint of the daemon, returning the parsed JSON dict.

        The file/command endpoints go through it (as opposed to run_code's SSE streaming).
        A non-200 response with a {"error": ...} body is raised as a RuntimeError.
        """
        with self._ensure_transport().request(
            "POST",
            path,
            body=json.dumps(payload).encode(),
            headers={"Content-Type": "application/json"},
        ) as resp:
            raw = resp.read().decode(errors="replace")
            if resp.status != 200:
                try:
                    message = json.loads(raw).get("error", raw)
                except json.JSONDecodeError:
                    message = raw
                raise RuntimeError(f"{path} failed: {message}")
            return json.loads(raw)


# ----- file / shell namespaces (attached to Sandbox, with a feel aligned to E2B) -----


class _Files:
    """sandbox.files.*: read/write/list directories in the sandbox filesystem (aligned with E2B's sandbox.files).

    Done by the in-VM daemon directly on the VM's own filesystem. Note the VM has a
    --read-only root + only /tmp writable -- writing outside /tmp raises a RuntimeError.
    """

    def __init__(self, sandbox: Sandbox) -> None:
        self._sb = sandbox

    def write(self, path: str, content: str) -> None:
        self._sb._post_json("/files/write", {"path": path, "content": content})

    def read(self, path: str) -> str:
        return self._sb._post_json("/files/read", {"path": path})["content"]

    def list(self, path: str) -> list[dict]:
        """List a directory, returning [{"name": str, "is_dir": bool}, ...]."""
        return self._sb._post_json("/files/list", {"path": path})["entries"]


class _Commands:
    """sandbox.commands.*: run shell commands in the sandbox (aligned with E2B's sandbox.commands)."""

    def __init__(self, sandbox: Sandbox) -> None:
        self._sb = sandbox

    def run(self, command: str, timeout_seconds: float | None = None) -> Execution:
        """Run a shell command, returning the same Execution as run_code (stdout/stderr/exit_code)."""
        payload = {
            "command": command,
            # Use `is None` rather than `or`: the latter would treat an explicitly passed 0 as "not passed" and fall back to the default.
            "timeout_seconds": (
                timeout_seconds
                if timeout_seconds is not None
                else self._sb.timeout_seconds
            ),
        }
        data = self._sb._post_json("/commands", payload)
        return Execution(
            stdout=data["stdout"],
            stderr=data["stderr"],
            exit_code=data["exit_code"],
        )
