"""Client SDK -- the interface users actually face when writing code.

Design goal: keep the feel as close to E2B as possible, so that after you've
studied your own implementation, going back to E2B's SDK feels familiar.
Typical usage:

    from microsandbox import Sandbox

    with Sandbox() as sandbox:
        execution = sandbox.run_code("print('hello from sandbox')")
        print(execution.stdout)

Stage 0/1: Sandbox automatically spawns a daemon subprocess locally and connects
        to it (spawn_local=True). At Stage 1, backend="docker" makes the daemon
        run the code inside a one-shot container -- switch isolation strategies
        with a single line, and run_code's usage stays exactly the same.
Stage 2+: Sandbox's responsibility expands to "request a new sandbox from the
        control plane, obtain its address, then connect to it." But the upper-level
        API of run_code / streaming consumption stays unchanged for the user.
"""

from __future__ import annotations

import json
import os
import pathlib
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
import uuid
from abc import ABC, abstractmethod
from collections.abc import Callable, Iterator
from typing import Any

from .protocol import EventType, Execution, ExecuteRequest, OutputEvent

# The channel between client and daemon is a point-to-point internal channel; it
# should never be intercepted by an environment proxy. By default urllib reads
# env vars like http_proxy, and Python only does exact/suffix matching for
# no_proxy -- it does not understand Windows-style wildcards (e.g. "127.*",
# "<local>"). In environments like WSL2 that inherit the host's proxy config, even
# requests to 127.0.0.1 get forwarded to the local proxy, and the proxy
# occasionally RSTs as it closes the connection, causing random
# ConnectionResetError in tests. Here we explicitly build a "no proxy" opener, and
# all of the client's requests go through it.
_DIRECT_OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))

# ---- Stage 2: resident-container topology ----
# These backend values represent the "ownership inversion": the daemon no longer
# runs on the host, but is run by the client via docker run -d as a long-lived
# resident inside a long-running container (corresponding to E2B's envd).
# "container" (2a): inside the container is a stateless subprocess; "kernel" (2b):
# inside the container is a resident Jupyter kernel, where variables persist across
# run_code calls. Both share the same "start a resident container" code; the only
# difference is which image to use and which --backend to tell the in-container
# daemon to use (see _spawn_resident_container).
_RESIDENT_BACKENDS = {"container", "kernel"}
# client's backend value -> which --backend the in-container daemon actually starts with.
_INNER_BACKEND = {"container": "local", "kernel": "kernel"}
# The in-container daemon always listens on this port; the host side maps it to a
# random free port (see _find_free_port), so that multiple sandboxes -- and any
# daemon that may already exist on the host -- don't collide on ports.
_CONTAINER_PORT = 49152
# Where the source is mounted inside the container (2a builds no image; mounting the
# host's src/ read-only is enough to run our package).
_CONTAINER_SRC = "/opt/microsandbox/src"

# ---- Stage 3: Firecracker microVM topology ----
# Isomorphic to Stage 2's resident container: the client hand-creates and owns the
# isolation environment (here a microVM), and the daemon resides inside the VM,
# exposed via vsock. The artifacts (firecracker binary / kernel / rootfs) are
# generated by scripts/build-rootfs.sh under the repo's vendor/ (see
# docs/STAGE3_DESIGN.md §6/§7).
_MICROVM_VSOCK_PORT = 1024   # vsock port the daemon listens on inside the VM (matches the rootfs's /init)
_MICROVM_GUEST_CID = 3       # guest's vsock CID (host is fixed at 2)
_MICROVM_VCPUS = 1
_MICROVM_MEM_MIB = 512       # a Jupyter kernel runs inside the VM; 256 is tight, so give 512


def _vendor_dir() -> pathlib.Path:
    """Artifacts directory: client.py is under src/microsandbox/, so the repo root is parents[2]."""
    return pathlib.Path(__file__).resolve().parents[2] / "vendor"


def _firecracker_api(
    sock_path: str, method: str, path: str, body: dict, timeout: float = 15.0
) -> int:
    """Send one request to Firecracker's REST API (HTTP over AF_UNIX), returning the status code.

    Operations like snapshot load/create can't be expressed via --config-file, so they
    must go through the API. api.sock may not yet have been created by firecracker, so
    poll and retry until timeout when the connection fails. Only the status line is read
    (the body is ignored).
    """
    payload = json.dumps(body).encode()
    head = (
        f"{method} {path} HTTP/1.1\r\nHost: localhost\r\n"
        f"Content-Type: application/json\r\nContent-Length: {len(payload)}\r\n"
        f"Connection: close\r\n\r\n"
    ).encode()
    deadline = time.time() + timeout
    while True:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.settimeout(2)
        try:
            sock.connect(sock_path)
        except OSError:
            sock.close()
            if time.time() > deadline:
                raise
            time.sleep(0.005)
            continue
        try:
            sock.sendall(head + payload)
            return int(sock.makefile("rb").readline().split(b" ")[1])
        finally:
            sock.close()


def _find_free_port() -> int:
    """Bind to :0 to let the kernel allocate a free port, release it immediately, and hand the port number to docker -p.

    There's a tiny race window between releasing and docker actually binding; good
    enough for Stage 2a, while more robust port / sandbox-pool management is a Stage 4
    matter.
    """
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


# ---- Stage 3: transport-layer abstraction (Transport) ----
#
# In Stages 0~2, the channel between client and daemon was always "HTTP/SSE over TCP",
# hardcoded into urllib calls. Stage 3's microVM switches the control channel to vsock
# (the host connects into the VM via Firecracker's UDS, see docs/STAGE3_DESIGN.md §4.1)
# -- the transport actually changes for the first time. To keep the main thread of
# "protocol bytes unchanged, only the underlying pipe swapped" valid, here we abstract
# "how to send one HTTP round-trip to the daemon" into Transport:
#   - _TcpTransport: wraps the existing urllib over TCP as-is, byte-for-byte identical
#     behavior (the four topologies local/docker/container/kernel, and the existing 42
#     tests, therefore all pass green without a single change).
#   - _VsockTransport: connects to Firecracker's vsock UDS, does the CONNECT handshake,
#     and hand-writes a minimal HTTP/1.1 over the raw socket (used at Stage 3b when
#     wiring up the microVM; this step writes and unit-tests it first, not yet against a
#     real VM).
# Sandbox's _stream / _post_json / _wait_until_healthy are all changed to send/receive
# via transport and no longer touch urllib directly -- the transport details are
# blocked off by this layer, so the upper-level logic is completely identical for
# TCP/vsock.


class _Response:
    """A response after one HTTP round-trip is normalized by the transport layer: a status code + a file-like.

    Both usages share it; the only difference is how the caller reads fp:
      - streaming (SSE): `for line in resp:` consumes line by line until the connection
        closes (EOF);
      - single-shot (JSON): `resp.read()` reads the whole body at once.
    fp is urllib's response object for _TcpTransport, and the socket's read file for
    _VsockTransport -- both support "line-by-line iteration" and read(), so the
    upper-level logic is indistinguishable across the two transports.
    """

    def __init__(
        self, status: int, fp: Any, on_close: Callable[[], None] | None = None
    ) -> None:
        self.status = status
        self.fp = fp
        self._on_close = on_close

    def __iter__(self) -> Iterator[bytes]:
        return iter(self.fp)

    def read(self) -> bytes:
        return self.fp.read()

    def close(self) -> None:
        try:
            self.fp.close()
        finally:
            if self._on_close is not None:
                self._on_close()

    def __enter__(self) -> "_Response":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class _Transport(ABC):
    """The abstraction of "how to send one HTTP request to the daemon and get the response back".
    When switching isolation/deployment form, all that needs to change is this layer
    (TCP->vsock); neither the protocol nor the upper-level API moves."""

    @abstractmethod
    def request(
        self,
        method: str,
        path: str,
        body: bytes | None = None,
        headers: dict[str, str] | None = None,
        timeout: float | None = None,
    ) -> _Response:
        """Send one HTTP request, returning a _Response. timeout=None means no timeout (blocking)."""
        raise NotImplementedError


class _TcpTransport(_Transport):
    """HTTP over TCP (the old path of Stages 0~2). Internally still uses urllib + the
    no-proxy opener, byte-for-byte identical behavior to before the refactor -- this is
    precisely why the existing tests pass green without modification."""

    def __init__(self, host: str, port: int) -> None:
        self._base = f"http://{host}:{port}"

    def request(
        self,
        method: str,
        path: str,
        body: bytes | None = None,
        headers: dict[str, str] | None = None,
        timeout: float | None = None,
    ) -> _Response:
        req = urllib.request.Request(
            self._base + path, data=body, headers=headers or {}, method=method
        )
        try:
            # When timeout=None, don't pass that argument, exactly replicating the
            # pre-refactor behavior of _DIRECT_OPENER.open(req) (in urllib, "not passing"
            # uses the global default, which differs subtly from an explicit None, so
            # keeping it as-is is the safest).
            resp = (
                _DIRECT_OPENER.open(req)
                if timeout is None
                else _DIRECT_OPENER.open(req, timeout=timeout)
            )
        except urllib.error.HTTPError as exc:
            # Non-2xx is an exception in urllib; normalize it into a _Response so the
            # upper layer (_post_json) handles it uniformly by status, consistent with the
            # vsock path. HTTPError is itself a file-like that supports read().
            return _Response(exc.code, exc)
        return _Response(resp.status, resp)


class _VsockTransport(_Transport):
    """HTTP over vsock (Stage 3's microVM control channel).

    Firecracker multiplexes the guest's vsock onto a single Unix domain socket (UDS) on
    the host. The handshake is a text protocol: after connecting to the UDS, send
    `CONNECT <port>\\n`, Firecracker replies `OK <hostport>\\n`, and from then on this
    byte stream is wired to the daemon listening on that vsock port inside the guest.
    Once the handshake is done, both sides still speak the same original HTTP/SSE -- so
    here we only need to hand-write a minimal HTTP/1.1 client over the raw socket.
    (urllib doesn't speak this CONNECT handshake, so _TcpTransport can't be reused.)
    """

    def __init__(self, uds_path: str, vsock_port: int) -> None:
        self._uds = uds_path
        self._vsock_port = vsock_port

    def request(
        self,
        method: str,
        path: str,
        body: bytes | None = None,
        headers: dict[str, str] | None = None,
        timeout: float | None = None,
    ) -> _Response:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.settimeout(timeout)  # None=blocking (used by streaming /execute); health check passes 1s
        try:
            sock.connect(self._uds)
            # 1. Firecracker vsock handshake: CONNECT <port> -> OK <hostport>
            sock.sendall(f"CONNECT {self._vsock_port}\n".encode())
            rfile = sock.makefile("rb")  # reading the response goes through it; writes always use sock.sendall, to avoid read/write buffers interfering
            ack = rfile.readline()
            if not ack.startswith(b"OK"):
                # e.g. nobody is listening on that vsock port inside the guest, so Firecracker replies non-OK.
                raise ConnectionError(f"vsock CONNECT rejected: {ack!r}")
            # 2. Hand-write the minimal HTTP/1.1 request line + headers + body
            head = [f"{method} {path} HTTP/1.1", "Host: sandbox", "Connection: close"]
            hdrs = dict(headers or {})
            if body is not None:
                hdrs.setdefault("Content-Length", str(len(body)))
            head += [f"{k}: {v}" for k, v in hdrs.items()]
            sock.sendall(("\r\n".join(head) + "\r\n\r\n").encode())
            if body:
                sock.sendall(body)
            # 3. Read the status line + skip the response headers, leaving rfile at the start of the body for the upper layer (both streaming and single-shot read from here)
            status_line = rfile.readline().decode("latin-1")
            status = int(status_line.split(" ", 2)[1])
            while True:
                line = rfile.readline()
                if line in (b"\r\n", b"\n", b""):
                    break
            return _Response(status, rfile, on_close=sock.close)
        except Exception:
            sock.close()
            raise


class Sandbox:
    """A client handle for a sandbox session.

    Args:
        host / port: daemon address.
        spawn_local: convenience switch. If True, the constructor automatically spawns a
                     daemon subprocess locally and connects to it, closing it
                     automatically on exit -- so you can get running with a single line
                     of code, without manually starting the server first. Stage 2+
                     replaces this with real "create a sandbox" logic.
        backend: execution/deployment strategy, not part of the wire protocol.
                 - "local" (Stage 0): host subprocess, almost no isolation.
                 - "docker" (Stage 1): host daemon, spawns a one-shot container per execution.
                 - "container" (Stage 2a): the daemon moves into a **resident container**
                   to run (envd-ified); the client is responsible for starting it via
                   docker run and docker rm -f on exit. Inside the container it uses the
                   stateless subprocess backend.
                 - "kernel" (Stage 2b): also a resident container, but the in-container
                   daemon hosts a resident Jupyter kernel -- variables persist across
                   run_code, a real stateful REPL (aligned with E2B). Build the agent
                   image first: docker build -t microsandbox-agent .
                 - "microvm" (Stage 3): runs the daemon inside a Firecracker microVM
                   (independent guest kernel + KVM boundary, the strongest isolation),
                   with the control channel over vsock and the kernel backend (stateful)
                   inside the VM. Prepare the vendor/ artifacts first: see
                   docs/STAGE3_DESIGN.md §6/§7.
        from_snapshot: only effective for backend="microvm". If True, restore from a
                   pre-warmed snapshot in milliseconds (skipping kernel boot + Jupyter
                   kernel cold start, ~30ms to ready vs ~0.94s cold start). Run
                   scripts/build-snapshot.sh first; currently single-instance (the
                   snapshot's vsock uds path is fixed, see §9).
    """

    def __init__(
        self,
        host: str = "127.0.0.1",
        port: int = 49152,
        spawn_local: bool = True,
        timeout_seconds: float = 30.0,
        backend: str = "local",
        from_snapshot: bool = False,
    ) -> None:
        self.host = host
        self.port = port
        self.timeout_seconds = timeout_seconds
        self.backend = backend
        self._from_snapshot = from_snapshot
        self._proc: subprocess.Popen | None = None   # host daemon subprocess (Stage 0/1)
        self._container: str | None = None           # resident sandbox container name (Stage 2)
        # Transport layer (Stage 3 abstraction): defaults to lazily constructing a TCP
        # one; the microVM pre-installs a vsock transport in _spawn_microvm. Separates
        # "how to connect" from "what to say once connected".
        self._transport: _Transport | None = None
        self._workdir: pathlib.Path | None = None      # microVM's per-VM working directory (Stage 3)
        self._console_log: pathlib.Path | None = None  # firecracker/guest serial log (for diagnostics)

        # Stage 2c: the file / shell namespaces, with a feel aligned to E2B's
        # sandbox.files / sandbox.commands. They only use host/port when called, so it's
        # enough to build them here (order doesn't matter).
        self.files = _Files(self)
        self.commands = _Commands(self)

        if spawn_local:
            # Stage 2's "inversion" shows up in this fork: the resident-container backend
            # has the client hand-start a container via docker run to put the daemon
            # inside; the other backends follow Stage 0/1's host subprocess. Both paths
            # connect to the same daemon and speak the same protocol.
            #
            # Safety-net: after _spawn_* succeeds, the container/subprocess is already up;
            # if the immediately following health check fails (the daemon won't start / is
            # too slow), the exception propagates out of __init__ -- at which point the
            # with statement hasn't entered __enter__, __exit__ never fires, and the
            # already-started container becomes an orphaned leftover. So here we close it
            # ourselves and then re-raise the exception (close is idempotent, so it's safe).
            try:
                if backend == "microvm" and from_snapshot:
                    self._restore_microvm()
                elif backend == "microvm":
                    self._spawn_microvm()
                elif backend in _RESIDENT_BACKENDS:
                    self._spawn_resident_container()
                else:
                    self._spawn_daemon()
                self._wait_until_healthy()
            except Exception:
                self.close()
                raise

    # ----- lifecycle -----

    def _spawn_daemon(self) -> None:
        """Spawn the daemon subprocess locally (Stage 0/1: the daemon stays on the host machine).

        Stage 1's isolation doesn't happen here, but inside the daemon's DockerBackend --
        the client is only responsible for passing the --backend switch to the daemon, and
        knows nothing about docker itself. Stage 2 didn't change this path, but **added** a
        _spawn_resident_container (putting the daemon into a resident container,
        corresponding to E2B's envd) to coexist with it; Stage 3 adds one more, "start a
        microVM via the orchestrator". All three paths connect to the same daemon.
        """
        self._proc = subprocess.Popen(
            [sys.executable, "-m", "microsandbox.server",
             "--host", self.host, "--port", str(self.port),
             "--backend", self.backend,
             "--log-level", "WARNING"],
            stdout=subprocess.DEVNULL,
            # Keep stderr piped: if the daemon fails immediately at startup (e.g. docker
            # unavailable), the reason must be brought back to the user. WARNING-level logs
            # are tiny and won't fill up the 64KB pipe buffer.
            stderr=subprocess.PIPE,
        )

    def _spawn_resident_container(self) -> None:
        """Stage 2a: docker run -d to start a resident container with the daemon running inside.

        Contrast with _spawn_daemon above (Popen a process on the host): here the
        isolation environment (the container) is hand-created and held long-term by the
        client -- this is Stage 2's "ownership inversion". Note the daemon's code
        (server.py) didn't change a single line; only the place it runs changed: this is
        exactly what the three-layer decoupling sets out to prove.

        2a deliberately builds no image: read-only mounting the host's src/ into the
        official python:3.12-slim is enough to let the container run our package, and code
        changes need no rebuild. Only when Stage 2b introduces the jupyter dependency does
        it switch to a Dockerfile that bakes the dependencies into the agent image.
        """
        # Pick the image by backend: container uses the official slim (2a, zero deps);
        # kernel uses the agent image (2b, with ipykernel/jupyter_client preinstalled,
        # requires docker build -t microsandbox-agent . first).
        from .backend import DEFAULT_AGENT_IMAGE, DEFAULT_DOCKER_IMAGE, DockerBackend

        image = {
            "container": DEFAULT_DOCKER_IMAGE,
            "kernel": DEFAULT_AGENT_IMAGE,
        }[self.backend]

        # Before starting the container, surface environment problems (docker not
        # installed/not running/image missing) with actionable guidance, rather than
        # guessing from logs after docker run fails. Reuse the same checks from Stage 1.
        problem = DockerBackend.check_available(image)
        if problem:
            raise RuntimeError(f"Failed to create resident sandbox container: {problem}")

        # Uniform prefix naming for the container: docker rm -f by name on close, and any
        # leftovers can be cleaned up by prefix in one shot
        # (docker ps -a --filter name=microsandbox-sandbox -q | xargs -r docker rm -f).
        self._container = f"microsandbox-sandbox-{uuid.uuid4().hex[:12]}"
        self.host = "127.0.0.1"
        self.port = _find_free_port()  # random free port on the host side, to avoid colliding with multiple sandboxes / the host daemon

        src_dir = pathlib.Path(__file__).resolve().parents[1]  # .../src
        inner_backend = _INNER_BACKEND[self.backend]

        cmd = [
            "docker", "run", "-d",
            "--name", self._container,
            "--pull", "never",                 # error immediately if the image is missing; never implicitly pull on the creation path
            # Publish the management port only to the local loopback: the host can connect, the outside network can't
            "-p", f"127.0.0.1:{self.port}:{_CONTAINER_PORT}",
            # Resource limits apply to the entire sandbox container (the daemon + all
            # executions within it share the same cgroup); this is exactly E2B's
            # per-sandbox quota model -- not Stage 1's per-execution one. pids-limit is set
            # to 128 (larger than DockerBackend's 64): Stage 1's container runs only one
            # python, whereas here the daemon also resides in the container, plus the
            # subprocess of each execution, so pid usage is higher.
            "--memory", "256m", "--memory-swap", "256m",
            "--cpus", "1.0", "--pids-limit", "128",
            "--read-only", "--tmpfs", "/tmp:rw,size=64m",
            "-v", f"{src_dir}:{_CONTAINER_SRC}:ro",       # read-only mount the source
            "-e", f"PYTHONPATH={_CONTAINER_SRC}",
            "-e", "PYTHONDONTWRITEBYTECODE=1",            # don't try to write .pyc under the read-only root
            "-e", "PYTHONUNBUFFERED=1",
            # Point HOME to the writable tmpfs: under the kernel backend, Jupyter needs to
            # write the kernel connection file and IPython needs to write its history
            # sqlite, which by default both land under HOME, while the root is
            # --read-only. Harmless to the container backend.
            "-e", "HOME=/tmp",
            image,
            # The daemon must listen on 0.0.0.0 to be reachable by the host via the mapped
            # port (the default 127.0.0.1 inside the container means nobody can connect in).
            # This is the only "config" difference on the server side; the code itself
            # doesn't change.
            "python", "-m", "microsandbox.server",
            "--host", "0.0.0.0", "--port", str(_CONTAINER_PORT),
            "--backend", inner_backend, "--log-level", "WARNING",
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            self._container = None  # if it didn't start, don't try to delete a nonexistent name in close
            raise RuntimeError(f"docker run failed to start the resident container: {proc.stderr.strip()}")

    def _spawn_microvm(self) -> None:
        """Stage 3: start a Firecracker microVM with the daemon running inside, exposed via vsock.

        Isomorphic to _spawn_resident_container above (the client owns the isolation
        environment's lifecycle), differing in only two points: (1) the isolation body
        changes from a container to a microVM (independent guest kernel + KVM boundary, the
        strongest isolation); (2) the control channel changes from TCP port mapping to
        vsock. The daemon (server.py) and the protocol didn't change a single line -- this
        is exactly what Stage 3 most wants to prove: switching isolation = switching the
        client's creation logic + switching the transport, with the protocol untouched.
        """
        vendor = _vendor_dir()
        fc_bin, kernel, rootfs = (
            vendor / "firecracker", vendor / "vmlinux", vendor / "rootfs.ext4")

        problem = self._check_microvm_available(fc_bin, kernel, rootfs)
        if problem:
            raise RuntimeError(f"Failed to create microVM: {problem}")

        # per-VM working directory: config, vsock UDS, api sock, console.log all go here (the whole thing is deleted on close).
        self._workdir = pathlib.Path(tempfile.mkdtemp(prefix="microsandbox-vm-"))
        uds = self._workdir / "fc.vsock"
        self._console_log = self._workdir / "console.log"

        # A single JSON declares the entire VM (during the learning phase, use
        # --config-file rather than per-item REST, for easy at-a-glance reading).
        config = {
            "boot-source": {
                "kernel_image_path": str(kernel),
                # root=/dev/vda read-only root; init=/init our minimal init; MSBACKEND selects the in-VM execution backend.
                "boot_args": (
                    "console=ttyS0 reboot=k panic=1 pci=off "
                    "root=/dev/vda ro init=/init MSBACKEND=kernel"
                ),
            },
            "drives": [{
                "drive_id": "rootfs",
                "path_on_host": str(rootfs),
                "is_root_device": True,
                "is_read_only": True,   # read-only root; all writes go to the in-VM tmpfs /tmp (aligned with Stage 2)
            }],
            "machine-config": {
                "vcpu_count": _MICROVM_VCPUS, "mem_size_mib": _MICROVM_MEM_MIB},
            # Firecracker multiplexes the guest vsock onto this UDS; the client's _VsockTransport connects to it.
            "vsock": {"guest_cid": _MICROVM_GUEST_CID, "uds_path": str(uds)},
        }
        config_path = self._workdir / "config.json"
        config_path.write_text(json.dumps(config))

        # firecracker's stdout/stderr (including the guest serial console) lands in a file
        # -- can't use PIPE: the guest console writes continuously, and a full PIPE buffer
        # would stall the VM. Read this file to diagnose startup failures.
        with open(self._console_log, "wb") as log_fh:
            self._proc = subprocess.Popen(
                [str(fc_bin), "--api-sock", str(self._workdir / "api.sock"),
                 "--config-file", str(config_path)],
                stdout=log_fh, stderr=subprocess.STDOUT,
            )
        # The daemon listens on vsock 1024 inside the VM; the host connects in via the uds.
        # The health check fires next in __init__, going through exactly this vsock
        # transport (_wait_until_healthy is already transport-agnostic).
        self._transport = _VsockTransport(str(uds), _MICROVM_VSOCK_PORT)

    @staticmethod
    def _check_microvm_available(
        fc_bin: pathlib.Path, kernel: pathlib.Path, rootfs: pathlib.Path
    ) -> str | None:
        """Surface environment problems before startup with actionable guidance (cf. DockerBackend.check_available)."""
        if not fc_bin.exists():
            return f"Missing firecracker binary ({fc_bin}); see docs/STAGE3_DESIGN.md §6 for download"
        if not kernel.exists():
            return f"Missing kernel vmlinux ({kernel}); see docs/STAGE3_DESIGN.md §6 for download"
        if not rootfs.exists():
            return f"Missing rootfs ({rootfs}); please run scripts/build-rootfs.sh first"
        if not os.path.exists("/dev/kvm"):
            return "/dev/kvm does not exist: (nested) hardware virtualization is not enabled on this machine"
        if not os.access("/dev/kvm", os.R_OK | os.W_OK):
            return ("No permission to access /dev/kvm: add the current user to the kvm group"
                    " (sudo usermod -aG kvm $USER) and restart WSL")
        return None

    def _microvm_log(self) -> str:
        """Grab the tail of the microVM's firecracker/guest serial log, only for startup-failure diagnostics."""
        if self._console_log is None:
            return ""
        try:
            return self._console_log.read_text(errors="replace")[-1500:].strip()
        except OSError:
            return ""

    def _restore_microvm(self) -> None:
        """Stage 3c: restore a microVM from a pre-generated snapshot -- skipping kernel boot
        and Jupyter kernel cold start, achieving millisecond-level readiness (cf.
        _spawn_microvm cold start ~0.94s, restore-to-ready ~30ms).

        Mechanism: a snapshot contains two artifacts -- vmstate (device/CPU state) +
        memfile (guest memory, already containing a hot kernel). Start an empty
        firecracker, pour the state back via the REST API `PUT /snapshot/load` + resume,
        and the VM continues running from its frozen point, with both the daemon and kernel
        already ready. Note rootfs.ext4 must still be at its original path (the snapshot
        stores only memory/device state; disk contents are still provided by the host's
        backing file).

        Known limitation (single-instance): the vsock uds path in the snapshot is fixed
        (vendor/snapshot/fc.vsock), so only one can be restored at a time (multiple would
        collide on the same socket path). Concurrent restore + a pre-warm pool require a
        per-VM uds override, which belongs to Stage 4.
        """
        vendor = _vendor_dir()
        snap = vendor / "snapshot"
        vmstate, memfile, uds = snap / "vmstate", snap / "memfile", snap / "fc.vsock"

        problem = self._check_microvm_available(
            vendor / "firecracker", vendor / "vmlinux", vendor / "rootfs.ext4")
        if problem:
            raise RuntimeError(f"Failed to restore microVM: {problem}")
        if not vmstate.exists() or not memfile.exists():
            raise RuntimeError(f"Missing snapshot ({snap}); please run scripts/build-snapshot.sh first")

        self._workdir = pathlib.Path(tempfile.mkdtemp(prefix="microsandbox-vm-"))
        self._console_log = self._workdir / "console.log"
        api_sock = self._workdir / "api.sock"
        uds.unlink(missing_ok=True)  # clear out the same-named socket left from last time; firecracker will re-listen on this fixed path

        with open(self._console_log, "wb") as log_fh:
            self._proc = subprocess.Popen(
                [str(vendor / "firecracker"), "--api-sock", str(api_sock)],
                stdout=log_fh, stderr=subprocess.STDOUT,
            )
        status = _firecracker_api(str(api_sock), "PUT", "/snapshot/load", {
            "snapshot_path": str(vmstate),
            "mem_backend": {"backend_type": "File", "backend_path": str(memfile)},
            "resume_vm": True,
        })
        if status not in (200, 204):
            raise RuntimeError(
                f"snapshot/load failed: HTTP {status}; {self._microvm_log()[-300:]}")
        self._transport = _VsockTransport(str(uds), _MICROVM_VSOCK_PORT)

    def _ensure_transport(self) -> _Transport:
        """Lazily construct the transport layer. Defaults to TCP (local/docker/container/
        kernel all use it); Stage 3b's microVM pre-installs a _VsockTransport in
        _spawn_microvm, so this won't override it. It's evaluated after spawn so it can
        pick up the final port the resident container is randomly mapped to on the host."""
        if self._transport is None:
            self._transport = _TcpTransport(self.host, self.port)
        return self._transport

    def _wait_until_healthy(self, attempts: int = 50, delay: float = 0.1) -> None:
        transport = self._ensure_transport()
        for _ in range(attempts):
            # If the daemon process has already exited, don't dumbly wait the full 5
            # seconds -- immediately read out its stderr as the error. For example, with the
            # docker backend when the image is missing, the daemon's startup check directly
            # prints the reason and exits.
            if self._proc is not None and self._proc.poll() is not None:
                detail = ""
                if self._proc.stderr is not None:
                    detail = self._proc.stderr.read().decode(errors="replace").strip()
                detail = detail or self._microvm_log()  # the microVM's firecracker log is in a file
                raise RuntimeError(
                    f"sandbox daemon exited at startup: {detail[-500:] or '(no stderr)'}"
                )
            try:
                with transport.request("GET", "/health", timeout=1) as resp:
                    if resp.status == 200:
                        return
            except Exception:
                time.sleep(delay)
        # Not ready within the time limit: the resident container/microVM appends the log
        # tail to the error for easier troubleshooting (the host daemon goes through the
        # poll branch above and throws early, never reaching here).
        detail = self._container_logs() or self._microvm_log()
        raise RuntimeError(
            "sandbox daemon did not become healthy in time"
            + (f": {detail[-500:]}" if detail else "")
        )

    def _container_logs(self) -> str:
        """Grab the tail of the resident container's logs, only for errors on startup failure. Any failure returns an empty string."""
        if self._container is None:
            return ""
        try:
            out = subprocess.run(
                ["docker", "logs", "--tail", "20", self._container],
                capture_output=True, text=True, timeout=5,
            )
            return (out.stdout + out.stderr).strip()
        except Exception:
            return ""

    def close(self) -> None:
        if self._proc is not None:
            self._proc.terminate()
            try:
                self._proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._proc.kill()
            self._proc = None
        if self._container is not None:
            # Kill and delete the entire resident sandbox container. Contrast with Stage
            # 1's timeout cleanup (which kills the one-shot execution container); here we
            # destroy the sandbox itself. docker rm -f does stop+rm together; failures such
            # as the container already not existing are all ignored (idempotent
            # safety-net).
            subprocess.run(
                ["docker", "rm", "-f", self._container],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
            self._container = None
        if self._workdir is not None:
            # self._proc above has already killed the firecracker process (= destroyed the
            # VM); here we clean up the per-VM working directory (config / vsock UDS / api
            # sock / console.log are all inside). ignore_errors is an idempotent safety-net.
            shutil.rmtree(self._workdir, ignore_errors=True)
            self._workdir = None

    def __enter__(self) -> "Sandbox":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()

    # ----- core API -----

    def run_code(
        self,
        code: str,
        language: str = "python",
        on_stdout: Callable[[str], None] | None = None,
        on_stderr: Callable[[str], None] | None = None,
    ) -> Execution:
        """Execute a piece of code, returning the aggregated Execution result.

        Optionally pass on_stdout / on_stderr callbacks to get streaming output in real
        time (e.g. print as it runs), while still ultimately returning the complete
        Execution.
        """
        execution = Execution()
        for event in self._stream(code, language):
            execution.events.append(event)
            if event.type == EventType.STDOUT:
                execution.stdout += event.data
                if on_stdout:
                    on_stdout(event.data)
            elif event.type == EventType.STDERR:
                execution.stderr += event.data
                if on_stderr:
                    on_stderr(event.data)
            elif event.type == EventType.ERROR:
                execution.error = (execution.error or "") + event.data
            elif event.type == EventType.END:
                execution.exit_code = event.exit_code
        return execution

    def _stream(self, code: str, language: str) -> Iterator[OutputEvent]:
        """Issue an execution request to the daemon, parsing the SSE stream line by line.

        How the request reaches the daemon is decided by the transport (TCP or vsock);
        here we only translate /execute's SSE response back into OutputEvents line by line
        -- completely identical across the two transports (before the refactor this was
        inlined on urllib).
        """
        request = ExecuteRequest(
            code=code, language=language, timeout_seconds=self.timeout_seconds
        )
        with self._ensure_transport().request(
            "POST",
            "/execute",
            body=request.to_json().encode(),
            headers={"Content-Type": "application/json"},
        ) as resp:
            for raw in resp:
                line = raw.decode(errors="replace").rstrip("\n")
                if not line.startswith("data: "):
                    continue
                payload = line[len("data: "):]
                if not payload:
                    continue
                yield OutputEvent.from_sse_payload(payload)

    def _post_json(self, path: str, payload: dict) -> dict:
        """POST a JSON to a non-streaming endpoint of the daemon, returning the parsed JSON dict.

        Stage 2c's file/command endpoints all go through it (as opposed to run_code's SSE
        streaming). A {"error": ...} in a non-200 response is raised as a RuntimeError.

        Non-2xx behaves differently across transports (urllib raises HTTPError, vsock is a
        plain response); normalization is delegated to the transport: here we only judge
        by resp.status, consistent across the two transports.
        """
        with self._ensure_transport().request(
            "POST",
            path,
            body=json.dumps(payload).encode(),
            headers={"Content-Type": "application/json"},
        ) as resp:
            raw = resp.read().decode(errors="replace")
            if resp.status != 200:
                try:
                    message = json.loads(raw).get("error", raw)
                except json.JSONDecodeError:
                    message = raw
                raise RuntimeError(f"{path} failed: {message}")
            return json.loads(raw)


# ----- Stage 2c: file / shell namespaces (attached to Sandbox, with a feel aligned to E2B) -----


class _Files:
    """sandbox.files.*: read/write/list directories in the sandbox filesystem (aligned with E2B's sandbox.files).

    Done by the daemon directly on the FS it resides on: for the container/kernel backend
    that's inside the container (in the sandbox), and for the local backend that's the
    host. Note the resident container is a --read-only root + only /tmp writable --
    writing outside /tmp raises a RuntimeError.
    """

    def __init__(self, sandbox: Sandbox) -> None:
        self._sb = sandbox

    def write(self, path: str, content: str) -> None:
        self._sb._post_json("/files/write", {"path": path, "content": content})

    def read(self, path: str) -> str:
        return self._sb._post_json("/files/read", {"path": path})["content"]

    def list(self, path: str) -> list[dict]:
        """List a directory, returning [{"name": str, "is_dir": bool}, ...]."""
        return self._sb._post_json("/files/list", {"path": path})["entries"]


class _Commands:
    """sandbox.commands.*: run shell commands in the sandbox (aligned with E2B's sandbox.commands)."""

    def __init__(self, sandbox: Sandbox) -> None:
        self._sb = sandbox

    def run(self, command: str, timeout_seconds: float | None = None) -> Execution:
        """Run a shell command, returning the same Execution as run_code (stdout/stderr/exit_code)."""
        payload = {
            "command": command,
            # Use `is None` rather than `or`: the latter would treat an explicitly passed 0 as "not passed" and fall back to the default.
            "timeout_seconds": (
                timeout_seconds
                if timeout_seconds is not None
                else self._sb.timeout_seconds
            ),
        }
        data = self._sb._post_json("/commands", payload)
        return Execution(
            stdout=data["stdout"],
            stderr=data["stderr"],
            exit_code=data["exit_code"],
        )
