// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: orchestrator/orchestrator.proto

// Package orchestrator is the gRPC contract between the api (the caller) and the
// per-machine orchestrator (the server). It mirrors E2B's orchestrator SandboxService
// (e2b-dev/infra: packages/orchestrator/orchestrator.proto). Stage 8b introduces this
// seam: the api stops calling the VM logic in-process and instead invokes it over gRPC,
// so the two could later live on different machines -- exactly E2B's api -> orchestrator
// boundary. See docs/STAGE8_DESIGN.md.

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SandboxConfig is what the api hands the orchestrator to shape a new sandbox.
//
// The field numbers (= 1, = 2, ...) are the *wire identity* of each field: protobuf
// encodes them, not the names, so a number must never change or be reused once shipped
// (that is how old and new builds stay compatible). Names are free to change.
type SandboxConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`                              // template/image name; "" means the default image
	FromSnapshot  bool                   `protobuf:"varint,2,opt,name=from_snapshot,json=fromSnapshot,proto3" json:"from_snapshot,omitempty"` // true: restore from the template's snapshot (fast, pool-eligible)
	Vcpu          uint32                 `protobuf:"varint,3,opt,name=vcpu,proto3" json:"vcpu,omitempty"`                                     // 0 = let the orchestrator pick its default (1)
	MemMb         uint32                 `protobuf:"varint,4,opt,name=mem_mb,json=memMb,proto3" json:"mem_mb,omitempty"`                      // 0 = orchestrator default (512)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	mi := &file_orchestrator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxConfig.ProtoReflect.Descriptor instead.
func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_orchestrator_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxConfig) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SandboxConfig) GetFromSnapshot() bool {
	if x != nil {
		return x.FromSnapshot
	}
	return false
}

func (x *SandboxConfig) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *SandboxConfig) GetMemMb() uint32 {
	if x != nil {
		return x.MemMb
	}
	return 0
}

type SandboxCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *SandboxConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCreateRequest) Reset() {
	*x = SandboxCreateRequest{}
	mi := &file_orchestrator_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateRequest) ProtoMessage() {}

func (x *SandboxCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateRequest.ProtoReflect.Descriptor instead.
func (*SandboxCreateRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SandboxCreateRequest) GetConfig() *SandboxConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SandboxCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxCreateResponse) Reset() {
	*x = SandboxCreateResponse{}
	mi := &file_orchestrator_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCreateResponse) ProtoMessage() {}

func (x *SandboxCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCreateResponse.ProtoReflect.Descriptor instead.
func (*SandboxCreateResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxCreateResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type SandboxDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxDeleteRequest) Reset() {
	*x = SandboxDeleteRequest{}
	mi := &file_orchestrator_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxDeleteRequest) ProtoMessage() {}

func (x *SandboxDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxDeleteRequest.ProtoReflect.Descriptor instead.
func (*SandboxDeleteRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *SandboxDeleteRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type SandboxListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxIds    []string               `protobuf:"bytes,1,rep,name=sandbox_ids,json=sandboxIds,proto3" json:"sandbox_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxListResponse) Reset() {
	*x = SandboxListResponse{}
	mi := &file_orchestrator_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxListResponse) ProtoMessage() {}

func (x *SandboxListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxListResponse.ProtoReflect.Descriptor instead.
func (*SandboxListResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxListResponse) GetSandboxIds() []string {
	if x != nil {
		return x.SandboxIds
	}
	return nil
}

var File_orchestrator_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1forchestrator/orchestrator.proto\x12\forchestrator\x1a\x1bgoogle/protobuf/empty.proto\"{\n" +
	"\rSandboxConfig\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12#\n" +
	"\rfrom_snapshot\x18\x02 \x01(\bR\ffromSnapshot\x12\x12\n" +
	"\x04vcpu\x18\x03 \x01(\rR\x04vcpu\x12\x15\n" +
	"\x06mem_mb\x18\x04 \x01(\rR\x05memMb\"K\n" +
	"\x14SandboxCreateRequest\x123\n" +
	"\x06config\x18\x01 \x01(\v2\x1b.orchestrator.SandboxConfigR\x06config\"6\n" +
	"\x15SandboxCreateResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"5\n" +
	"\x14SandboxDeleteRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"6\n" +
	"\x13SandboxListResponse\x12\x1f\n" +
	"\vsandbox_ids\x18\x01 \x03(\tR\n" +
	"sandboxIds2\xec\x01\n" +
	"\x0eSandboxService\x12Q\n" +
	"\x06Create\x12\".orchestrator.SandboxCreateRequest\x1a#.orchestrator.SandboxCreateResponse\x12D\n" +
	"\x06Delete\x12\".orchestrator.SandboxDeleteRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a!.orchestrator.SandboxListResponseB-Z+microsandbox/services/pkg/grpc/orchestratorb\x06proto3"

var (
	file_orchestrator_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_orchestrator_proto_rawDesc), len(file_orchestrator_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_orchestrator_proto_rawDescData
}

var file_orchestrator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_orchestrator_orchestrator_proto_goTypes = []any{
	(*SandboxConfig)(nil),         // 0: orchestrator.SandboxConfig
	(*SandboxCreateRequest)(nil),  // 1: orchestrator.SandboxCreateRequest
	(*SandboxCreateResponse)(nil), // 2: orchestrator.SandboxCreateResponse
	(*SandboxDeleteRequest)(nil),  // 3: orchestrator.SandboxDeleteRequest
	(*SandboxListResponse)(nil),   // 4: orchestrator.SandboxListResponse
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_orchestrator_orchestrator_proto_depIdxs = []int32{
	0, // 0: orchestrator.SandboxCreateRequest.config:type_name -> orchestrator.SandboxConfig
	1, // 1: orchestrator.SandboxService.Create:input_type -> orchestrator.SandboxCreateRequest
	3, // 2: orchestrator.SandboxService.Delete:input_type -> orchestrator.SandboxDeleteRequest
	5, // 3: orchestrator.SandboxService.List:input_type -> google.protobuf.Empty
	2, // 4: orchestrator.SandboxService.Create:output_type -> orchestrator.SandboxCreateResponse
	5, // 5: orchestrator.SandboxService.Delete:output_type -> google.protobuf.Empty
	4, // 6: orchestrator.SandboxService.List:output_type -> orchestrator.SandboxListResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orchestrator_orchestrator_proto_init() }
func file_orchestrator_orchestrator_proto_init() {
	if File_orchestrator_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_orchestrator_proto_rawDesc), len(file_orchestrator_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_orchestrator_proto = out.File
	file_orchestrator_orchestrator_proto_goTypes = nil
	file_orchestrator_orchestrator_proto_depIdxs = nil
}
